server:
  port: "8080"
  readTimeout: 10
  writeTimeout: 10

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "brewkar"
  sslmode: "disable"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "your-secret-key-here"
  accessTokenExp: 15     # minutes
  refreshTokenExp: 10080 # 7 days in minutes

s3:
  bucket: "brewkar-images"
  region: "us-east-1"
  endpoint: ""

